# Database Connector Secret for PostgreSQL
#
# This secret contains the admin credentials for a PostgreSQL server.
# vCluster will use these credentials to automatically create a new database
# and user for the vCluster instance.
#
# Usage:
#   1. Update the values below with your PostgreSQL server details
#   2. kubectl apply -f connector-postgres-secret.yaml
#   3. Create vCluster with: vcluster create my-vcluster -f connector-postgres-values.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-connector
  namespace: default  # Must be in the same namespace as your vCluster
type: Opaque
stringData:
  # Database type (required): mysql or postgres
  type: "postgres"
  
  # Database server host (required)
  host: "postgres-server.default.svc.cluster.local"
  
  # Database server port (optional, defaults to 5432 for PostgreSQL)
  port: "5432"
  
  # Admin username with privileges to create databases and users (required)
  adminUser: "postgres"
  
  # Admin password (required)
  adminPassword: "your-admin-password"
  
  # SSL mode (optional, defaults to 'disable')
  # Options: disable, require, verify-ca, verify-full
  sslMode: "disable"
  
  # TLS/SSL certificates (optional, required if sslMode is verify-ca or verify-full)
  # caCert: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # clientCert: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # clientKey: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----

---
# Example vCluster values using the connector
# Save this as connector-postgres-values.yaml and use with:
# vcluster create my-vcluster -f connector-postgres-values.yaml

# controlPlane:
#   backingStore:
#     database:
#       external:
#         enabled: true
#         connector: "postgres-connector"



