# Database Connector Secret for MySQL
#
# This secret contains the admin credentials for a MySQL server.
# vCluster will use these credentials to automatically create a new database
# and user for the vCluster instance.
#
# Usage:
#   1. Update the values below with your MySQL server details
#   2. kubectl apply -f connector-mysql-secret.yaml
#   3. Create vCluster with: vcluster create my-vcluster -f connector-mysql-values.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-connector
  namespace: default  # Must be in the same namespace as your vCluster
type: Opaque
stringData:
  # Database type (required): mysql or postgres
  type: "mysql"
  
  # Database server host (required)
  host: "mysql-server.default.svc.cluster.local"
  
  # Database server port (optional, defaults to 3306 for MySQL)
  port: "3306"
  
  # Admin username with privileges to create databases and users (required)
  adminUser: "root"
  
  # Admin password (required)
  adminPassword: "your-admin-password"
  
  # TLS/SSL configuration (optional)
  # tls: "true"
  # caCert: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # clientCert: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # clientKey: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----

---
# Example vCluster values using the connector
# Save this as connector-mysql-values.yaml and use with:
# vcluster create my-vcluster -f connector-mysql-values.yaml

# controlPlane:
#   backingStore:
#     database:
#       external:
#         enabled: true
#         connector: "mysql-connector"



